services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\ExtensionGenerator:
        arguments:
        - '@session'
        - '%kernel.project_dir%'
        public: true
